### ISSUE TITLE
Add a Load method

### ISSUE THREAD

**Issue by toburger** [matthid/Yaaf.FSharp.Scripting#1]
Like Reference and Open you should also add a Load method, to load scripts interactively.
```fsharp
fsiSession.EvalInteraction("#load \"MyScript.fsx\"")
```
becomes
```fsharp
fsiSession.Load("MyScript.fsx")
```

**Comment by matthid** [comment]
Good point!
`EvalScript` actually falls back to that (https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/fsi/fsi.fs#L2119). But having `Load` as well definitely makes sense.
